### ISSUE TITLE
More rigorous unit/integration testing

### ISSUE THREAD

**Issue by computablee** [computablee/DotMP#45]
Currently, most all of the tests are integration tests. I would love to see some fine-grained unit tests for DotMP. Anything helps and this is very open-ended, but we should start by creating a new XUnit tester for unit testing that's capable of testing the `internal` classes and methods that DotMP mostly consists of.

**Comment by ayan-joshi** [comment]
Hello I want to work on this issue can u assign it to me @computablee

**Comment by computablee** [comment]
Done

**Comment by computablee** [comment]
@ayan-joshi Just a head's up, I'm going ahead and adding some tests for the parallel for reduction method tonight, since a lot of it is untested and I can fairly quickly write some tests for that. Let me know if this affects you at all.

**Comment by computablee** [comment]
Added some more tests in #82.

**Comment by computablee** [comment]
I am closing this issue since the repo has recently achieved 100% code coverage (:partying_face:). I went ahead and worked through this myself since I did not see that the repo had been forked for this issue.
