### ISSUE TITLE
Lock-free `Schedule.Dynamic` and `Schedule.Guided`

### ISSUE THREAD

**Issue by computablee** [computablee/DotMP#46]
The current schedulers for `dynamic` and `guided` scheduling as found in `Iter.cs` use mutual exclusion to ensure that race conditions don't occur. I have thought about ways to implement lock-free scheduling via clever use of atomics and rollback, but to be quite honest I've never been great at lock-free algorithms. With hacktoberfest coming up, this would be an excellent first issue for someone not super familiar with DotMP or C#, but with lots of parallel programming experience.

**Comment by Thehackerash** [comment]
please assign this issue to me

**Comment by computablee** [comment]
Sure, assigned.

**Comment by computablee** [comment]
@Thehackerash Any updates? I am starting to prepare for the next release of DotMP, and would like to know if you are working on this or if I should open up the issue for reassignment.
