### ISSUE TITLE
Documentation not present in current Nuget Build (date 9/29/2023)

### ISSUE THREAD

**Issue by bj-rutledge** [computablee/DotMP#52]
The current build on NuGet does not contain/expose the documentation for structs, classes, methods, etc. No summaries are available in object browser or IntelliSense. 

![image](https://github.com/computablee/DotMP/assets/86386474/2d218ffe-0d95-4af2-82f4-9f875ad661f7)

**Comment by computablee** [comment]
Thank you, I'll look into this and make sure to add a new entry to the makefile that ensures that packing is done properly.
