### ISSUE TITLE
Fix linter issues in CI pipeline

### ISSUE THREAD

**Issue by computablee** [computablee/DotMP#64]
Currently the linting check is failing on `jscpd`, which is a linting tool for detecting copy+pasted code. Optimally, all checks in a repo should pass (that's what checks are for, right?)

So this issue is to ensure that `jscpd` starts passing without impacting anything else in the codebase. A successful PR will

1. Keep all integration and unit tests passing
2. Make minimal changes to increase modularity of the code
3. Get all linting tests passing

Please consult the output of `jscpd` on the main branch (under the checks menu) to see what all needs to change.

**Comment by mihica-khare** [comment]
Please assign to me

**Comment by computablee** [comment]
Assigned. Thank you!

**Comment by computablee** [comment]
@mihica-khare I have a PR draft open which is addressing several refactoring issues. I have lots of spare time tonight and I'd like to get this done as soon as possible. Since I noticed you haven't forked the repo yet, I am going to go ahead and assign this issue to myself just so that we can get all CI passing. Please let me know if there's a different issue you'd like to be assigned to and I'll prioritize you.
